      for (i = 0; i < this.candidates.length; i++)
            if (this.candidates[i] === p) return i;	            if (this.candidates[i] === p) return i;
        return this.candidates.length + 1;	        return this.candidates.length + 1;
<<<<<<< HEAD	
    }	


    this.prefers = function(p) {	
        return this.rank(p) < this.rank(this.fiance);	
    }	
=======	
    };	    };


    this.prefers = function(p) {	    this.prefers = function(p) {
        return this.rank(p) < this.rank(this.fiance);	        return this.rank(p) < this.rank(this.fiance);
    };	    };
>>>>>>> master	


    this.nextCandidate = function() {	    this.nextCandidate = function() {
        if (candidateIndex >= this.candidates.length) return null;	        if (candidateIndex >= this.candidates.length) return null;
        return this.candidates[candidateIndex++];	        return this.candidates[candidateIndex++];
<<<<<<< HEAD	
    }	
=======	
    };	    };
>>>>>>> master	


    this.engageTo = function(p) {	    this.engageTo = function(p) {
        if (p.fiance) {	        if (p.fiance) {
@@ -43,23 +34,18 @@ function Person(name) {
        if (this.fiance) this.fiance.fiance = null;	        if (this.fiance) this.fiance.fiance = null;
        this.fiance = p;	        this.fiance = p;
        // console.log(this.name, this.fiance.name)	        // console.log(this.name, this.fiance.name)
<<<<<<< HEAD	
    }	
=======	
    };	    };
>>>>>>> master	


    this.swapWith = function(p) {	    this.swapWith = function(p) {
        console.log("%s & %s swap partners", this.name, p.name);	        console.log("%s & %s swap partners", this.name, p.name);
        var thisFiance = this.fiance;	        var thisFiance = this.fiance;
        var pFiance = p.fiance;	        var pFiance = p.fiance;
        this.engageTo(pFiance);	        this.engageTo(pFiance);
        p.engageTo(thisFiance);	        p.engageTo(thisFiance);
<<<<<<< HEAD	
    }	
=======	
    };	    };
>>>>>>> master	
}	}


function isStable(guys, gals) {	function isStable(guys, gals) {
@@ -76,81 +62,72 @@ function engageEveryone(guys) {
        done = true;	        done = true;
        for (var i = 0; i < guys.length; i++) {	        for (var i = 0; i < guys.length; i++) {
            var guy = guys[i];	            var guy = guys[i];
<<<<<<< HEAD	
            console.log(guy.name)	
=======	
            console.log(guy.name);	            console.log(guy.name);
>>>>>>> master	


            if (!guy.fiance) {	            if (!guy.fiance) {
                done = false;	                done = false;


                var gal = guy.nextCandidate();	                var gal = guy.nextCandidate();
<<<<<<< HEAD	
                console.log(gal.name)	                console.log(gal.name)
                if (!gal.fiance || gal.prefers(guy)) {	
                    guy.engageTo(gal);	
                    console.log("engage", guy.name, gal.name)	
=======	
                console.log(gal.name);	
                if (!gal.fiance || gal.prefers(guy)) {	                if (!gal.fiance || gal.prefers(guy)) {
                    guy.engageTo(gal);	                    guy.engageTo(gal);
                    console.log("engage", guy.name, gal.name);	                    console.log("engage", guy.name, gal.name);
>>>>>>> master	                    if (!gal.fiance || gal.prefers(guy)) {
                        guy.engageTo(gal);
                        console.log("engage", guy.name, gal.name);
                    }
                }	                }
                // console.log(guy.name, guy.fiance.name)
            }	            }
            // console.log(guy.name, guy.fiance.name)	
        }	        }
    } while (!done);	        while (!done);
}	    }

    function doMarriage() {

        var joanna = new Person("Joanna");
        var annabelle = new Person("Annabelle");
        var violet = new Person("Violet");

        var google = new Person("Google");
        var fb = new Person("Facebook");
        // var twitter = new Person("Twitter");
        // var linkedin=new Person('Linkedin');

        joanna.candidates = [google, fb];
        annabelle.candidates = [fb, google];
        violet.candidates = [google, fb];

        google.candidates = [annabelle, violet, joanna];
        fb.candidates = [joanna, annabelle, violet];
        // twitter.candidates = [annabelle, joanna, violet];
        // linkedin.candidates=[joanna,annabelle,violet];


function doMarriage() {	        var people = [joanna, annabelle, violet];

        var companies = [google, fb, ];
    var joanna = new Person("Joanna");	
    var frances = new Person("Frances");	
    var violet = new Person("Violet");	        var smallerSet

        if (people.length <= companies.length)
    var google = new Person("Google");	            smallerSet = people
    var fb = new Person("Facebook");	        else
    // var twitter = new Person("Twitter");	            smallerSet = companies
    // var linkedin=new Person('Linkedin');	

        engageEveryone(smallerSet)
    joanna.candidates = [google, fb];	        var smallerSet;
    frances.candidates = [fb, google];	        if (people.length <= companies.length)
    violet.candidates = [google, fb];	            smallerSet = people;

        else
    google.candidates = [frances, violet, joanna];	            smallerSet = companies;
    fb.candidates = [joanna, frances, violet];	
    // twitter.candidates = [frances, joanna, violet];	        engageEveryone(smallerSet);
    // linkedin.candidates=[joanna,frances,violet];	

        for (var i = 0; i < smallerSet.length; i++) {
    var people = [joanna, frances, violet];	            console.log("%s is engaged to %s", smallerSet[i].name, smallerSet[i].fiance.name);
    var companies = [google, fb, ];	        }

        console.log("Stable = %s", isStable(people, companies) ? "Yes" : "No");
<<<<<<< HEAD	        joanna.swapWith(annabelle);
    var smallerSet	        console.log("Stable = %s", isStable(people, companies) ? "Yes" : "No");
    if (people.length <= companies.length)	
        smallerSet = people	
    else	
        smallerSet = companies	

    engageEveryone(smallerSet)	
=======	
    var smallerSet;	
    if (people.length <= companies.length)	
        smallerSet = people;	
    else	
        smallerSet = companies;	

    engageEveryone(smallerSet);	
>>>>>>> master	

    for (var i = 0; i < smallerSet.length; i++) {	
        console.log("%s is engaged to %s", smallerSet[i].name, smallerSet[i].fiance.name);	
    }	    }
    console.log("Stable = %s", isStable(people, companies) ? "Yes" : "No");	
    joanna.swapWith(frances);	
    console.log("Stable = %s", isStable(people, companies) ? "Yes" : "No");	
}	


doMarriage(); 	    doMarriage(); 
